#!/bin/bash

echo "========================================="
echo "Applying BoardGuru Database Migrations"
echo "========================================="
echo ""
echo "This script will apply the following migrations:"
echo "1. Create meetings table and related tables"
echo "2. Fix user table RLS policies"
echo ""
echo "Please copy and run these SQL files in your Supabase SQL editor:"
echo ""
echo "Step 1: Create Meetings Table"
echo "------------------------------"
echo "File: supabase/migrations/create_meetings_table.sql"
echo ""
echo "Step 2: Fix User Table Policies"
echo "--------------------------------"
echo "File: supabase/migrations/fix_user_table_policies.sql"
echo ""
echo "========================================="
echo "Instructions:"
echo "1. Go to your Supabase dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Copy the content of each SQL file above"
echo "4. Run each migration in order"
echo "5. Verify tables are created in Table Editor"
echo "========================================="
echo ""
echo "After applying migrations, restart your development server:"
echo "npm run dev"
echo ""