#!/bin/bash

echo "========================================="
echo "Applying BoardGuru Database Migrations"
echo "========================================="
echo ""
echo "RECOMMENDED: Use Option 3 for most cases!"
echo ""
echo "OPTION 1: Fresh start (drops and recreates everything):"
echo "--------------------------------------------------------"
echo "File: supabase/migrations/001_create_all_tables_ordered.sql"
echo "Use if: You want to start completely fresh"
echo ""
echo "OPTION 2: Fix existing tables (adds missing columns):"
echo "--------------------------------------------------------"
echo "File: supabase/migrations/002_fix_existing_tables.sql"
echo "Use if: You get 'column does not exist' errors"
echo ""
echo "OPTION 3: Create missing tables (RECOMMENDED):"
echo "--------------------------------------------------------"
echo "File: supabase/migrations/003_create_missing_tables.sql"
echo "Use if: You get 'relation boards does not exist' or similar errors"
echo "This safely creates only missing tables without affecting existing ones"
echo ""
echo "========================================="
echo "Instructions:"
echo "1. Go to your Supabase dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Copy and paste: supabase/migrations/003_create_missing_tables.sql"
echo "4. Click 'Run'"
echo "5. Verify in Table Editor that 'boards' table now exists"
echo "========================================="
echo ""
echo "The migrations will:"
echo "  - Create/fix organizations table"
echo "  - Create/fix users table"
echo "  - Create/fix boards table"
echo "  - Create/fix meetings table"
echo "  - Create/fix all junction tables"
echo "  - Add all missing columns"
echo "  - Set up RLS policies"
echo "  - Add triggers and functions"
echo ""
echo "After applying migrations, restart your development server:"
echo "npm run dev"
echo ""