# Example secrets file - DO NOT commit actual secrets
# This is a template showing the structure
apiVersion: v1
kind: Secret
metadata:
  name: boardguru-secrets
  labels:
    app: boardguru
type: Opaque
stringData:
  # Database
  database-url: "postgresql://username:password@hostname:5432/database"
  
  # Redis
  redis-url: "redis://hostname:6379"
  
  # Authentication
  nextauth-secret: "your-nextauth-secret-key-here"
  
  # Supabase
  supabase-anon-key: "your-supabase-anon-key"
  supabase-service-role-key: "your-supabase-service-role-key"
  
  # Email SMTP
  smtp-user: "your-smtp-username"
  smtp-pass: "your-smtp-password"
  
  # AI APIs
  anthropic-api-key: "your-anthropic-api-key"
  openai-api-key: "your-openai-api-key"
  
  # AWS Credentials (if not using IAM roles)
  aws-access-key-id: "your-aws-access-key"
  aws-secret-access-key: "your-aws-secret-key"
  
  # TLS Certificates
  tls-cert: |
    -----BEGIN CERTIFICATE-----
    your-certificate-here
    -----END CERTIFICATE-----
  tls-key: |
    -----BEGIN PRIVATE KEY-----
    your-private-key-here
    -----END PRIVATE KEY-----
---
# Example of using AWS Secrets Manager (preferred for production)
apiVersion: v1
kind: Secret
metadata:
  name: boardguru-secrets-from-aws
  annotations:
    # This would be handled by external-secrets operator
    external-secrets.io/backend: aws-secrets-manager
    external-secrets.io/key: boardguru-production-secrets
type: Opaque
data: {} # Populated by external-secrets operator
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  labels:
    app: boardguru
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "your-github-username",
          "password": "your-github-token",
          "auth": "base64-encoded-username:token"
        }
      }
    }
---
# Service account token for GitHub Actions deployments
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-token
  annotations:
    kubernetes.io/service-account.name: github-actions-sa
type: kubernetes.io/service-account-token