apiVersion: v1
kind: Service
metadata:
  name: boardguru-app-service
  labels:
    app: boardguru
    tier: app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/api/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: boardguru
    tier: app
    version: green  # Points to green by default
---
apiVersion: v1
kind: Service
metadata:
  name: boardguru-app-blue-service
  labels:
    app: boardguru
    tier: app
    version: blue
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: boardguru
    tier: app
    version: blue
---
apiVersion: v1
kind: Service
metadata:
  name: boardguru-app-green-service
  labels:
    app: boardguru
    tier: app
    version: green
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: boardguru
    tier: app
    version: green
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boardguru-app
  labels:
    app: boardguru
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/boardguru-app-role
automountServiceAccountToken: false