import type {
  ESGMetric,
  ESGFramework,
  ESGCategory,
  ESGDataPoint,
  ESGConfiguration,
  ESGRisk,
  ESGOpportunity,
  ESGRecommendation,
  ESGScorecard,
  OrganizationId,
  UserId
} from '@/types/esg'

// Standard ESG Metrics Database
export const ESG_METRICS_SEED_DATA: Omit<ESGMetric, 'id'>[] = [
  // Environmental Metrics
  {
    category: 'Environmental',
    subcategory: 'Climate Change',
    name: 'Total GHG Emissions (Scope 1)',
    description: 'Direct greenhouse gas emissions from owned or controlled sources',
    unit: 'tCO2e',
    target: 1000,
    weight: 15,
    framework: ['GRI', 'SASB', 'TCFD', 'CDP'],
    dataSource: 'Internal Monitoring',
    calculationMethod: 'Sum of all direct emissions from combustion, process, fugitive sources',
    reportingFrequency: 'Monthly',
    isRequired: true,
    tags: ['climate', 'emissions', 'carbon']
  },
  {
    category: 'Environmental',
    subcategory: 'Climate Change',
    name: 'Total GHG Emissions (Scope 2)',
    description: 'Indirect greenhouse gas emissions from purchased energy',
    unit: 'tCO2e',
    target: 2000,
    weight: 12,
    framework: ['GRI', 'SASB', 'TCFD', 'CDP'],
    dataSource: 'Utility Bills',
    calculationMethod: 'Electricity consumption × emission factors',
    reportingFrequency: 'Monthly',
    isRequired: true,
    tags: ['climate', 'emissions', 'energy']
  },
  {
    category: 'Environmental',
    subcategory: 'Energy',
    name: 'Total Energy Consumption',
    description: 'Total energy consumed from all sources',
    unit: 'MWh',
    target: 5000,
    weight: 10,
    framework: ['GRI', 'SASB'],
    dataSource: 'Energy Management System',
    calculationMethod: 'Sum of all energy sources (electricity, gas, renewables)',
    reportingFrequency: 'Monthly',
    isRequired: true,
    tags: ['energy', 'consumption']
  },
  {
    category: 'Environmental',
    subcategory: 'Energy',
    name: 'Renewable Energy Percentage',
    description: 'Percentage of total energy from renewable sources',
    unit: '%',
    target: 50,
    weight: 12,
    framework: ['GRI', 'SASB', 'CDP'],
    dataSource: 'Energy Procurement',
    calculationMethod: 'Renewable energy / Total energy consumption × 100',
    reportingFrequency: 'Quarterly',
    isRequired: false,
    tags: ['renewable', 'energy', 'sustainability']
  },
  {
    category: 'Environmental',
    subcategory: 'Water',
    name: 'Total Water Consumption',
    description: 'Total water consumed across all operations',
    unit: 'm³',
    target: 10000,
    weight: 8,
    framework: ['GRI', 'SASB'],
    dataSource: 'Water Meters',
    calculationMethod: 'Sum of municipal water + groundwater + recycled water',
    reportingFrequency: 'Monthly',
    isRequired: true,
    tags: ['water', 'consumption', 'resource']
  },
  {
    category: 'Environmental',
    subcategory: 'Waste',
    name: 'Total Waste Generated',
    description: 'Total waste generated by operations',
    unit: 'tonnes',
    target: 500,
    weight: 7,
    framework: ['GRI', 'SASB'],
    dataSource: 'Waste Management Records',
    calculationMethod: 'Sum of hazardous + non-hazardous waste',
    reportingFrequency: 'Monthly',
    isRequired: true,
    tags: ['waste', 'circular-economy']
  },
  {
    category: 'Environmental',
    subcategory: 'Waste',
    name: 'Waste Recycling Rate',
    description: 'Percentage of waste that is recycled or reused',
    unit: '%',
    target: 80,
    weight: 6,
    framework: ['GRI'],
    dataSource: 'Waste Management Records',
    calculationMethod: 'Recycled waste / Total waste × 100',
    reportingFrequency: 'Quarterly',
    isRequired: false,
    tags: ['recycling', 'waste', 'circular-economy']
  },

  // Social Metrics
  {
    category: 'Social',
    subcategory: 'Employee Wellbeing',
    name: 'Employee Satisfaction Score',
    description: 'Average employee satisfaction rating from surveys',
    unit: 'score (1-10)',
    target: 8.5,
    weight: 12,
    framework: ['GRI', 'SASB'],
    dataSource: 'Employee Surveys',
    calculationMethod: 'Weighted average of satisfaction survey responses',
    reportingFrequency: 'Quarterly',
    isRequired: true,
    tags: ['satisfaction', 'wellbeing', 'culture']
  },
  {
    category: 'Social',
    subcategory: 'Diversity & Inclusion',
    name: 'Gender Diversity Ratio',
    description: 'Percentage of women in total workforce',
    unit: '%',
    target: 50,
    weight: 10,
    framework: ['GRI', 'SASB'],
    dataSource: 'HR Systems',
    calculationMethod: 'Female employees / Total employees × 100',
    reportingFrequency: 'Quarterly',
    isRequired: true,
    tags: ['diversity', 'gender', 'inclusion']
  },
  {
    category: 'Social',
    subcategory: 'Diversity & Inclusion',
    name: 'Leadership Diversity',
    description: 'Percentage of leadership positions held by underrepresented groups',
    unit: '%',
    target: 40,
    weight: 11,
    framework: ['GRI', 'SASB'],
    dataSource: 'HR Systems',
    calculationMethod: 'Diverse leaders / Total leadership positions × 100',
    reportingFrequency: 'Quarterly',
    isRequired: true,
    tags: ['diversity', 'leadership', 'representation']
  },
  {
    category: 'Social',
    subcategory: 'Health & Safety',
    name: 'Lost Time Injury Rate',
    description: 'Rate of workplace injuries resulting in lost work time',
    unit: 'per 200,000 hours',
    target: 0.5,
    weight: 15,
    framework: ['GRI', 'SASB'],
    dataSource: 'Safety Management System',
    calculationMethod: 'Lost time injuries × 200,000 / Total work hours',
    reportingFrequency: 'Monthly',
    isRequired: true,
    tags: ['safety', 'injury', 'workplace']
  },
  {
    category: 'Social',
    subcategory: 'Training & Development',
    name: 'Training Hours per Employee',
    description: 'Average training hours completed per employee annually',
    unit: 'hours',
    target: 40,
    weight: 8,
    framework: ['GRI'],
    dataSource: 'Learning Management System',
    calculationMethod: 'Total training hours / Number of employees',
    reportingFrequency: 'Quarterly',
    isRequired: false,
    tags: ['training', 'development', 'skills']
  },
  {
    category: 'Social',
    subcategory: 'Community',
    name: 'Community Investment',
    description: 'Total investment in community programs and initiatives',
    unit: 'USD',
    target: 100000,
    weight: 6,
    framework: ['GRI'],
    dataSource: 'Financial Records',
    calculationMethod: 'Sum of all community program expenditures',
    reportingFrequency: 'Quarterly',
    isRequired: false,
    tags: ['community', 'investment', 'social-impact']
  },

  // Governance Metrics
  {
    category: 'Governance',
    subcategory: 'Board Composition',
    name: 'Board Independence',
    description: 'Percentage of independent directors on the board',
    unit: '%',
    target: 75,
    weight: 15,
    framework: ['GRI', 'SASB'],
    dataSource: 'Board Records',
    calculationMethod: 'Independent directors / Total directors × 100',
    reportingFrequency: 'Annually',
    isRequired: true,
    tags: ['governance', 'independence', 'board']
  },
  {
    category: 'Governance',
    subcategory: 'Board Composition',
    name: 'Board Gender Diversity',
    description: 'Percentage of women on the board of directors',
    unit: '%',
    target: 40,
    weight: 12,
    framework: ['GRI', 'SASB'],
    dataSource: 'Board Records',
    calculationMethod: 'Female directors / Total directors × 100',
    reportingFrequency: 'Annually',
    isRequired: true,
    tags: ['governance', 'diversity', 'board']
  },
  {
    category: 'Governance',
    subcategory: 'Ethics & Compliance',
    name: 'Ethics Training Completion',
    description: 'Percentage of employees who completed ethics training',
    unit: '%',
    target: 100,
    weight: 10,
    framework: ['GRI'],
    dataSource: 'Learning Management System',
    calculationMethod: 'Trained employees / Total employees × 100',
    reportingFrequency: 'Annually',
    isRequired: true,
    tags: ['ethics', 'compliance', 'training']
  },
  {
    category: 'Governance',
    subcategory: 'Risk Management',
    name: 'Risk Assessment Coverage',
    description: 'Percentage of business processes covered by formal risk assessment',
    unit: '%',
    target: 95,
    weight: 11,
    framework: ['GRI'],
    dataSource: 'Risk Management System',
    calculationMethod: 'Assessed processes / Total critical processes × 100',
    reportingFrequency: 'Quarterly',
    isRequired: true,
    tags: ['risk', 'assessment', 'governance']
  },
  {
    category: 'Governance',
    subcategory: 'Transparency',
    name: 'Data Privacy Compliance',
    description: 'Compliance score for data privacy regulations',
    unit: 'score (0-100)',
    target: 95,
    weight: 13,
    framework: ['GRI'],
    dataSource: 'Compliance Audits',
    calculationMethod: 'Weighted average of compliance audit scores',
    reportingFrequency: 'Quarterly',
    isRequired: true,
    tags: ['privacy', 'compliance', 'data']
  },
  {
    category: 'Governance',
    subcategory: 'Executive Compensation',
    name: 'CEO Pay Ratio',
    description: 'Ratio of CEO compensation to median employee compensation',
    unit: 'ratio',
    target: 50,
    weight: 7,
    framework: ['GRI', 'SASB'],
    dataSource: 'Payroll Systems',
    calculationMethod: 'CEO total compensation / Median employee compensation',
    reportingFrequency: 'Annually',
    isRequired: false,
    tags: ['compensation', 'equity', 'governance']
  }
]

// Sample ESG Risks
export const ESG_RISKS_SEED_DATA: Omit<ESGRisk, 'id'>[] = [
  {
    category: 'Environmental',
    title: 'Carbon Tax Exposure',
    description: 'Potential impact of new carbon pricing mechanisms on operational costs',
    impact: 'High',
    likelihood: 'Medium',
    riskScore: 75,
    mitigation: [
      'Implement energy efficiency programs',
      'Increase renewable energy procurement',
      'Develop carbon offset strategy'
    ],
    owner: 'Chief Sustainability Officer',
    dueDate: '2025-06-30',
    status: 'Mitigating'
  },
  {
    category: 'Environmental',
    title: 'Water Scarcity Risk',
    description: 'Risk of water shortages affecting operations in key regions',
    impact: 'Medium',
    likelihood: 'High',
    riskScore: 65,
    mitigation: [
      'Implement water recycling systems',
      'Diversify water sources',
      'Conduct water stress assessments'
    ],
    owner: 'Operations Director',
    dueDate: '2025-03-31',
    status: 'Assessing'
  },
  {
    category: 'Social',
    title: 'Talent Retention Challenge',
    description: 'Risk of losing key talent due to poor work-life balance and compensation',
    impact: 'High',
    likelihood: 'Medium',
    riskScore: 70,
    mitigation: [
      'Enhance employee benefits package',
      'Implement flexible work arrangements',
      'Conduct regular compensation reviews'
    ],
    owner: 'Chief People Officer',
    dueDate: '2025-04-30',
    status: 'Mitigating'
  },
  {
    category: 'Social',
    title: 'Supply Chain Labor Practices',
    description: 'Risk of human rights violations in supply chain operations',
    impact: 'Critical',
    likelihood: 'Low',
    riskScore: 60,
    mitigation: [
      'Conduct supplier audits',
      'Implement supplier code of conduct',
      'Establish grievance mechanisms'
    ],
    owner: 'Chief Procurement Officer',
    dueDate: '2025-12-31',
    status: 'Monitoring'
  },
  {
    category: 'Governance',
    title: 'Cybersecurity Breach',
    description: 'Risk of data breach affecting customer and stakeholder trust',
    impact: 'Critical',
    likelihood: 'Medium',
    riskScore: 85,
    mitigation: [
      'Enhance cybersecurity infrastructure',
      'Conduct regular security audits',
      'Implement employee security training'
    ],
    owner: 'Chief Information Security Officer',
    dueDate: '2025-02-28',
    status: 'Mitigating'
  },
  {
    category: 'Governance',
    title: 'Regulatory Compliance Gap',
    description: 'Risk of non-compliance with evolving ESG reporting regulations',
    impact: 'High',
    likelihood: 'High',
    riskScore: 80,
    mitigation: [
      'Monitor regulatory developments',
      'Upgrade ESG reporting systems',
      'Train compliance team on new requirements'
    ],
    owner: 'Chief Compliance Officer',
    dueDate: '2025-05-31',
    status: 'Mitigating'
  }
]

// Sample ESG Opportunities
export const ESG_OPPORTUNITIES_SEED_DATA: Omit<ESGOpportunity, 'id'>[] = [
  {
    category: 'Environmental',
    title: 'Solar Panel Installation',
    description: 'Install solar panels on facilities to reduce energy costs and carbon footprint',
    potentialImpact: 'High',
    effort: 'Medium',
    timeframe: 'Long',
    estimatedValue: 500000,
    actionItems: [
      'Conduct feasibility study',
      'Secure financing',
      'Select installation partner',
      'Install and commission systems'
    ],
    owner: 'Facilities Manager',
    status: 'Planning'
  },
  {
    category: 'Environmental',
    title: 'Waste Reduction Program',
    description: 'Implement comprehensive waste reduction and circular economy initiatives',
    potentialImpact: 'Medium',
    effort: 'Low',
    timeframe: 'Short',
    estimatedValue: 150000,
    actionItems: [
      'Conduct waste audit',
      'Implement recycling programs',
      'Partner with waste management companies',
      'Train employees on waste reduction'
    ],
    owner: 'Sustainability Manager',
    status: 'In Progress'
  },
  {
    category: 'Social',
    title: 'Diversity & Inclusion Program',
    description: 'Launch comprehensive D&I program to improve workplace culture and performance',
    potentialImpact: 'High',
    effort: 'Medium',
    timeframe: 'Medium',
    estimatedValue: 300000,
    actionItems: [
      'Establish D&I council',
      'Develop inclusive hiring practices',
      'Implement bias training',
      'Create employee resource groups'
    ],
    owner: 'Chief People Officer',
    status: 'Identified'
  },
  {
    category: 'Social',
    title: 'Employee Wellness Program',
    description: 'Enhance employee wellness programs to improve satisfaction and productivity',
    potentialImpact: 'Medium',
    effort: 'Low',
    timeframe: 'Short',
    estimatedValue: 200000,
    actionItems: [
      'Survey employee wellness needs',
      'Partner with wellness providers',
      'Launch wellness challenges',
      'Provide mental health support'
    ],
    owner: 'HR Director',
    status: 'Planning'
  },
  {
    category: 'Governance',
    title: 'ESG Data Management System',
    description: 'Implement advanced ESG data management and reporting system',
    potentialImpact: 'High',
    effort: 'High',
    timeframe: 'Long',
    estimatedValue: 750000,
    actionItems: [
      'Evaluate ESG software solutions',
      'Implement chosen platform',
      'Integrate with existing systems',
      'Train users on new system'
    ],
    owner: 'Chief Technology Officer',
    status: 'Identified'
  },
  {
    category: 'Governance',
    title: 'Board Skills Enhancement',
    description: 'Enhance board capabilities with ESG expertise and diverse perspectives',
    potentialImpact: 'Medium',
    effort: 'Low',
    timeframe: 'Medium',
    estimatedValue: 100000,
    actionItems: [
      'Assess current board skills matrix',
      'Identify skill gaps',
      'Recruit diverse board members',
      'Provide ESG training to board'
    ],
    owner: 'Board Secretary',
    status: 'Planning'
  }
]

// Sample ESG Recommendations
export const ESG_RECOMMENDATIONS_SEED_DATA: Omit<ESGRecommendation, 'id'>[] = [
  {
    category: 'Environmental',
    priority: 'High',
    title: 'Accelerate Renewable Energy Transition',
    description: 'Increase renewable energy procurement to meet 2030 carbon neutrality goals',
    rationale: 'Current renewable energy percentage (25%) is below industry average (35%) and insufficient for climate targets',
    expectedImpact: 'Reduce Scope 2 emissions by 40% and improve environmental score by 12 points',
    implementation: {
      phases: [
        {
          name: 'Assessment & Planning',
          duration: '2 months',
          tasks: [
            'Energy audit of all facilities',
            'Renewable energy market analysis',
            'Financial feasibility study'
          ],
          deliverables: [
            'Energy consumption baseline',
            'Renewable energy procurement strategy',
            'Investment plan'
          ],
          milestones: ['Baseline established', 'Strategy approved']
        },
        {
          name: 'Procurement & Implementation',
          duration: '4 months',
          tasks: [
            'Issue RFPs for renewable energy',
            'Negotiate power purchase agreements',
            'Install on-site renewable systems'
          ],
          deliverables: [
            'Signed PPAs',
            'Installation contracts',
            'Commissioned systems'
          ],
          milestones: ['Contracts signed', 'Systems operational']
        }
      ],
      totalCost: 2500000,
      totalDuration: '6 months',
      dependencies: ['Management approval', 'Capital budget allocation', 'Regulatory permits'],
      risks: ['Energy price volatility', 'Installation delays', 'Grid connection issues']
    },
    timeline: '6 months',
    resources: ['Energy Manager', 'Procurement Team', 'External Consultants'],
    successMetrics: [
      'Increase renewable energy to 60%',
      'Reduce Scope 2 emissions by 40%',
      'Achieve positive ROI within 5 years'
    ],
    status: 'Pending'
  },
  {
    category: 'Social',
    priority: 'Medium',
    title: 'Enhance Employee Mental Health Support',
    description: 'Expand mental health and wellbeing programs to improve employee satisfaction',
    rationale: 'Employee satisfaction score (7.2) below target (8.5) with stress identified as key factor',
    expectedImpact: 'Improve employee satisfaction by 1.5 points and reduce turnover by 20%',
    implementation: {
      phases: [
        {
          name: 'Program Design',
          duration: '1 month',
          tasks: [
            'Survey employee mental health needs',
            'Research best practices',
            'Design comprehensive program'
          ],
          deliverables: [
            'Needs assessment report',
            'Program design document',
            'Budget proposal'
          ],
          milestones: ['Needs identified', 'Program approved']
        },
        {
          name: 'Implementation & Launch',
          duration: '3 months',
          tasks: [
            'Partner with mental health providers',
            'Train managers on mental health awareness',
            'Launch employee assistance programs'
          ],
          deliverables: [
            'Provider partnerships',
            'Manager training program',
            'Employee resource portal'
          ],
          milestones: ['Partners onboarded', 'Program launched']
        }
      ],
      totalCost: 200000,
      totalDuration: '4 months',
      dependencies: ['HR leadership support', 'Employee engagement', 'Provider partnerships'],
      risks: ['Low participation rates', 'Stigma concerns', 'Budget constraints']
    },
    timeline: '4 months',
    resources: ['HR Team', 'Mental Health Providers', 'Internal Communications'],
    successMetrics: [
      'Achieve 8.5+ employee satisfaction score',
      'Reduce voluntary turnover to <10%',
      'Achieve 80% program participation'
    ],
    status: 'Pending'
  },
  {
    category: 'Governance',
    priority: 'Critical',
    title: 'Strengthen Cybersecurity Governance',
    description: 'Enhance cybersecurity governance framework and board oversight capabilities',
    rationale: 'Current cybersecurity governance score (65%) below industry benchmark (85%) with increasing threat landscape',
    expectedImpact: 'Improve governance score by 20 points and reduce security risk exposure by 50%',
    implementation: {
      phases: [
        {
          name: 'Assessment & Framework Design',
          duration: '2 months',
          tasks: [
            'Conduct cybersecurity maturity assessment',
            'Benchmark against industry standards',
            'Design enhanced governance framework'
          ],
          deliverables: [
            'Maturity assessment report',
            'Gap analysis',
            'Governance framework document'
          ],
          milestones: ['Assessment completed', 'Framework approved']
        },
        {
          name: 'Implementation & Training',
          duration: '4 months',
          tasks: [
            'Implement new governance processes',
            'Train board on cyber risk oversight',
            'Establish regular reporting mechanisms'
          ],
          deliverables: [
            'Updated policies and procedures',
            'Board training program',
            'Cyber risk dashboard'
          ],
          milestones: ['Processes implemented', 'Board trained']
        }
      ],
      totalCost: 500000,
      totalDuration: '6 months',
      dependencies: ['Board commitment', 'CISO leadership', 'Technology investments'],
      risks: ['Evolving threat landscape', 'Resource constraints', 'Change resistance']
    },
    timeline: '6 months',
    resources: ['CISO', 'Board of Directors', 'External Security Consultants'],
    successMetrics: [
      'Achieve 90%+ cybersecurity governance score',
      'Reduce security incidents by 50%',
      'Complete board cyber training program'
    ],
    status: 'Approved'
  }
]

// Default ESG Configuration
export const DEFAULT_ESG_CONFIGURATION = (organizationId: OrganizationId): ESGConfiguration => ({
  organizationId,
  framework: ['GRI'],
  reportingPeriod: 'Quarterly',
  industryBenchmarks: true,
  peerComparison: false,
  enabledCategories: ['Environmental', 'Social', 'Governance'],
  customMetrics: [],
  weightings: [
    { category: 'Environmental', weight: 33.33 },
    { category: 'Social', weight: 33.33 },
    { category: 'Governance', weight: 33.34 }
  ],
  dataQualityThresholds: {
    minimumVerificationLevel: 'Internal',
    dataFreshnessThreshold: 90,
    completenessThreshold: 80
  },
  notificationSettings: {
    scoreUpdates: true,
    benchmarkChanges: true,
    riskAlerts: true,
    opportunityAlerts: true,
    reportingDeadlines: true,
    dataQualityIssues: true
  }
})